-- =============================================================
-- 04_grants.sql
-- Grants minimum required privileges for dbt and the Streamlit
-- app to function. Run as SYSADMIN or ACCOUNTADMIN.
-- =============================================================

USE ROLE SYSADMIN;

-- Grant usage on warehouse
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;

-- Grant all privileges on the database to SYSADMIN
GRANT ALL PRIVILEGES ON DATABASE LEARNING_DB TO ROLE SYSADMIN;

-- Grant privileges on all schemas
GRANT ALL PRIVILEGES ON SCHEMA LEARNING_DB.RAW     TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON SCHEMA LEARNING_DB.STAGING  TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON SCHEMA LEARNING_DB.MART     TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON SCHEMA LEARNING_DB.CI_STAGING TO ROLE SYSADMIN;

-- Grant table and view privileges
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA LEARNING_DB.RAW       TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA LEARNING_DB.STAGING    TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA LEARNING_DB.MART       TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA LEARNING_DB.CI_STAGING TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS  IN SCHEMA LEARNING_DB.STAGING    TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS  IN SCHEMA LEARNING_DB.CI_STAGING TO ROLE SYSADMIN;

-- Future grants so new objects are covered automatically
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA LEARNING_DB.RAW        TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA LEARNING_DB.STAGING     TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA LEARNING_DB.MART        TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA LEARNING_DB.CI_STAGING  TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA LEARNING_DB.STAGING     TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA LEARNING_DB.CI_STAGING  TO ROLE SYSADMIN;

-- Confirm grants applied
SHOW GRANTS ON DATABASE LEARNING_DB;
